In [1]:
import numpy as np
import keras
import pandas
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

Using TensorFlow backend.


In [16]:
## bring in data to scale so that testing data is transformed with the same scaling function
data = np.array(pandas.read_csv("./training_noavg.csv", header=0))
## Have to drop all the rows that have nan values because they will not help with net
## clean out rows with nan values
data = data[~np.isnan(data).any(axis=1)]
X = data[:,0:8]

scaler = StandardScaler()
X = scaler.fit_transform(X)

test1 = np.array(pandas.read_csv("./test1.csv", header=0))
test2 = np.array(pandas.read_csv("./test2.csv", header=0))
test3 = np.array(pandas.read_csv("./test3.csv", header=0))
test1 = test1[:,0:8]
test2 = test2[:,0:8]
test3 = test3[:,0:8]
test1 = test1[~np.isnan(test1).any(axis=1)]
test2 = test2[~np.isnan(test2).any(axis=1)]
test3 = test3[~np.isnan(test3).any(axis=1)]
print(test1.shape)
test = np.vstack((test1,test2,test3))

test = scaler.transform( test )

print(test.shape)

(14, 8)
(36, 8)


In [17]:
model = keras.models.load_model('MLN.model')
model.load_weights('MLN.weights')

In [19]:
preds = model.predict(test, batch_size=1, verbose=1, steps=None)

#print('Predicted:', preds[:])
for i in range(0,36):
    print(np.argmax(preds[i,]))
    print(preds[i])

36/36 [==============================] - 1s 21ms/step
0
[9.9972159e-01 1.5968618e-04 1.1864946e-04]
0
[9.99707758e-01 1.87634781e-04 1.04638755e-04]
0
[9.9789029e-01 7.2141958e-04 1.3882895e-03]
0
[9.989511e-01 5.167439e-04 5.322162e-04]
0
[9.9261510e-01 7.5424381e-04 6.6306996e-03]
0
[9.9920374e-01 4.3745179e-04 3.5875969e-04]
0
[0.9904212  0.00144124 0.0081375 ]
0
[9.9963927e-01 1.9248696e-04 1.6824802e-04]
0
[9.9928242e-01 3.0315580e-04 4.1447039e-04]
0
[9.9974638e-01 1.5775024e-04 9.5761425e-05]
0
[9.9973148e-01 1.6664247e-04 1.0195105e-04]
0
[9.9973720e-01 1.7404708e-04 8.8845729e-05]
0
[9.9970835e-01 1.6403901e-04 1.2761576e-04]
0
[9.9974662e-01 1.7622366e-04 7.7121040e-05]
1
[0.00153411 0.995652   0.00281398]
1
[6.160449e-04 9.987489e-01 6.350375e-04]
1
[3.9185164e-04 9.9923086e-01 3.7728454e-04]
1
[2.7163792e-04 9.9942029e-01 3.0804746e-04]
1
[2.1198661e-04 9.9958497e-01 2.0300722e-04]
1
[5.1277818e-04 9.9856216e-01 9.2505309e-04]
1
[5.6899071e-04 9.9885035e-01 5.8059767e-04]
1