In [5]:
import numpy as np
import keras
import pandas
from sklearn import preprocessing

In [6]:
test = np.array(pandas.read_csv("~/S19-team2-project/testdata.csv", header=0))
print(test.shape)

(5, 8)


In [7]:
model = keras.models.load_model('MLN.model')
model.load_weights('MLN.weights')

In [28]:
preds = model.predict(test, batch_size=1, verbose=1, steps=None)

print('Predicted:', preds[:])

5/5 [==============================] - 0s 5ms/step
Predicted: [[9.9932134e-01 1.8115676e-04 4.9745210e-04]
 [9.9932361e-01 1.8151272e-04 4.9483951e-04]
 [9.9931884e-01 1.8075264e-04 5.0044531e-04]
 [9.9932086e-01 1.8107945e-04 4.9802195e-04]
 [9.9932349e-01 1.8149643e-04 4.9496116e-04]]
